name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
      placeholder: "I would like the application to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've thought about
      placeholder: "I considered using..."

  - type: dropdown
    id: category
    attributes:
      label: Feature category
      description: What area does this feature relate to?
      options:
        - Audio routing / PipeWire functionality
        - User interface / UX
        - Profile management
        - Game detection
        - System tray / notifications
        - Keyboard shortcuts
        - Settings / configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples
      placeholder: Screenshots, mockups, or links to similar features in other applications

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: This feature is specific to Steam Audio Isolator (not a general PipeWire/Steam feature request)
          required: true
